"""Actual failed preunlock acquisition ends without unlock or a fake cleaner fact."""
import pytest
import uart2_protocol as uart
from edge_store import EdgeStore
from hardware.tests.test_mcu_work_preparation import library, runtime, exchange, original_scope, configured, start_values, take_samples
from hardware.tests.test_mcu_opening_gate import prepared, grant
from hardware.tests.test_mcu_clean_execution import enable, advance
from hardware.tests.test_mcu_clean_intent import save_intent
from hardware.tests.test_mcu_clean_confirmation import held_result
from hardware.tests.test_mcu_delivery_execution import facts, events

NAME = "WORK_PREUNLOCK_WEIGHT_READY"


def test_failed_preunlock_finishes_only_after_exact_custody_without_any_unlock_or_human_confirmation(runtime, tmp_path):
    execution = enable(runtime)
    lib, endpoint, preparation, *_ = runtime
    start, failed, now = prepared(runtime, tmp_path, clean=True, mode="unavailable", saved=False)
    assert failed["measurementKind"] == "UNAVAILABLE" and failed["measurementElapsedMs"] == 5000
    now = advance(runtime, now, 60000)
    state = exchange(runtime, "QUERY_WORK", original_scope(start, clean=True), now=now)[0][1]
    assert state["status"] == "RUNNING" and state["phase"] == "CLEAN_FINALIZING"
    store = EdgeStore(str(tmp_path / "failed-before-unlock.db"))
    store.initialize()
    try:
        assert store.acquire_work_slot("CLEAN", start["operationUid"], 1, {"phase": "NATIVE_CLEAN"})
        occupancy = store.get_work_slot()
        save_intent(runtime, start, NAME, 0, now, store)
        writes = lib.TestFacts_Writes()
        assert lib.McuWorkPreparation_Poll(preparation, endpoint, now)
        result = held_result(runtime, start, now)
        assert result["finishReason"] == "FAILED" and result["cleanActionSequence"] == 0
        assert result["initialKind"] == "UNAVAILABLE" and result["initialFaultCode"] == "WEIGHT_TIMEOUT"
        assert result["initialMeasurementUid"] == failed["measurementUid"]
        assert result["initialMcuEventSequence"] == failed["mcuEventSequence"]
        assert result["initialSourceMcuBootId"] == 42 and result["completedUptimeMs"] == failed["uptimeMs"] == 5000
        assert result["finalKind"] == "NOT_TAKEN" and result["finalMeasurementUid"] == "00000000-0000-0000-0000-000000000000"
        assert result["finalWeightGrams"] == 0 and result["finalSampleCount"] == 0
        assert not result["physicalCloseConfirmed"] and not result["negativeWeightAnomaly"] and result["deliveryRoundCount"] == 0
        assert result["originCommandUid"] == start["mcuCommandUid"] and result["originCommandSequence"] == start["commandSequence"]
        assert result["configVersion"] == start["configVersion"]
        assert facts(runtime, now)["measurementSequence"] == 1 and not facts(runtime, now)["cleanLockPowered"]
        assert not facts(runtime, now)["pb6Output"] and not facts(runtime, now)["pb7Output"]
        assert events(runtime, now)[0][1]["status"] == "NOT_FOUND" and lib.TestFacts_Writes() == writes
        assert store.list_native_result_report_tasks() == []
        receipt = store.save_native_mcu_result(uart.encode_payload("WORK_RESULT", result))
        assert exchange(runtime, "RESULT_SAVED", payload=receipt["savedPayload"], now=now)[0][1]["status"] == "RELEASED"
        assert store.get_work_slot() == occupancy
        assert [row["state"] for row in store.list_native_result_report_tasks()] == ["PENDING_CLASSIFICATION"]
        now = advance(runtime, now, 60000)
        # Timer ticks may refresh the existing 00 output; no mechanical command
        # or energized output is generated by foreground result finalization.
        assert facts(runtime, now)["measurementSequence"] == 1 and not facts(runtime, now)["cleanLockPowered"]
        assert not facts(runtime, now)["pb6Output"] and not facts(runtime, now)["pb7Output"] and execution
    finally:
        store.close()


def test_interrupted_initial_clean_measurement_retains_partial_attempt_as_failed_without_unlock(runtime, tmp_path):
    execution = enable(runtime)
    configured(runtime, applied=True)
    start = start_values("START_CLEAN_OPERATION")
    assert exchange(runtime, "START_CLEAN_OPERATION", start)[0][1]["outcome"] == "ACCEPTED"
    now = take_samples(runtime, [300])
    lib, endpoint, preparation, *_ = runtime
    # Explicit acquisition interruption, not a claim of automatic clean update
    # or expiry detection. This is already a real terminal measurement kind.
    assert lib.McuWeightRun_Interrupt(lib.TestPreparation_Weight(preparation), 1, now)
    now = advance(runtime, now, 0)
    store = EdgeStore(str(tmp_path / "interrupted-preunlock.db"))
    store.initialize()
    try:
        failed = save_intent(runtime, start, NAME, 0, now, store)
        assert failed["measurementKind"] == "INTERRUPTED" and failed["sampleCount"] == 1
        assert lib.McuWorkPreparation_Poll(preparation, endpoint, now)
        result = held_result(runtime, start, now)
        assert result["finishReason"] == "FAILED" and result["cleanActionSequence"] == 0
        assert result["initialKind"] == "INTERRUPTED" and result["initialFaultCode"] == "MEASUREMENT_INTERRUPTED"
        assert result["initialElapsedMs"] == 20 and result["initialSampleCount"] == 1
        assert result["initialMeasurementUid"] == failed["measurementUid"] and result["completedUptimeMs"] == failed["uptimeMs"]
        assert result["finalKind"] == "NOT_TAKEN" and not result["physicalCloseConfirmed"]
        assert events(runtime, now)[0][1]["status"] == "NOT_FOUND" and execution
    finally:
        store.close()


@pytest.mark.parametrize("count", [1, 4])
def test_insufficient_initial_samples_preserve_original_count_without_a_valid_weight(runtime, tmp_path, count):
    execution = enable(runtime)
    configured(runtime, applied=True)
    start = start_values("START_CLEAN_OPERATION")
    assert exchange(runtime, "START_CLEAN_OPERATION", start)[0][1]["outcome"] == "ACCEPTED"
    now = take_samples(runtime, [300] * count)
    now = advance(runtime, now, 5000 - now)
    store = EdgeStore(str(tmp_path / "insufficient-preunlock.db"))
    store.initialize()
    try:
        failed = save_intent(runtime, start, NAME, 0, now, store)
        now = advance(runtime, now, 0)
        result = held_result(runtime, start, now)
        assert result["initialKind"] == "UNAVAILABLE" and result["initialSampleCount"] == count
        assert result["initialWeightGrams"] == 0 and result["initialElapsedMs"] == 5000
        assert result["initialMeasurementUid"] == failed["measurementUid"]
        assert result["finalKind"] == "NOT_TAKEN" and not result["physicalCloseConfirmed"]
        assert not facts(runtime, now)["cleanLockPowered"] and execution
    finally:
        store.close()


@pytest.mark.parametrize("mode", ["stable", "median"])
def test_available_initial_clean_weight_is_not_finalized_as_failure(runtime, tmp_path, mode):
    execution = enable(runtime)
    lib = runtime[0]
    assert lib.ActuatorRuntime_SetDoorTarget(1)
    start, initial, now = prepared(runtime, tmp_path, clean=True, mode=mode, saved=True)
    now = advance(runtime, now, 0)
    assert exchange(runtime, "QUERY_WORK", original_scope(start, clean=True), now=now)[0][1]["phase"] == "CLEAN_WAIT_FIRST_UNLOCK"
    name, command = grant(start, initial, clean=True)
    assert exchange(runtime, name, command, now=now)[0][1]["outcome"] == "ACCEPTED"
    assert facts(runtime, now)["cleanLockPowered"] and execution


@pytest.mark.parametrize("case", ["no_receipt", "wrong_digest", "wrong_type", "empty_slot", "future_poll", "old_poll"])
def test_missing_or_inexact_custody_and_invalid_poll_time_cannot_freeze_failure(runtime, tmp_path, case):
    execution = enable(runtime)
    saved = case in {"empty_slot", "future_poll", "old_poll"}
    start, failed, now = prepared(runtime, tmp_path, clean=True, mode="unavailable", saved=saved)
    lib, endpoint, preparation, *_ = runtime
    poll_at = now
    if case in {"wrong_digest", "wrong_type"}:
        receipt = dict(mcuBootId=42, mcuEventSequence=failed["mcuEventSequence"], eventMessageType=NAME,
            eventDigestSha256=uart.compute_process_event_digest(NAME, uart.encode_payload(NAME, failed)))
        receipt.update({"eventDigestSha256": "00" * 32} if case == "wrong_digest" else {"eventMessageType": "WORK_PREOPEN_WEIGHT_READY"})
        assert exchange(runtime, "PROCESS_EVENT_SAVED", receipt, now=now)[0][1]["status"] == "IDENTITY_CONFLICT"
    elif case == "empty_slot":
        lib.McuProcessEventSlot_Init(lib.TestPreparation_Process(endpoint), 42)
    elif case == "future_poll":
        poll_at += 1
    elif case == "old_poll":
        poll_at -= 1
    writes = lib.TestFacts_Writes()
    assert lib.McuWorkPreparation_Poll(preparation, endpoint, poll_at)
    assert exchange(runtime, "QUERY_WORK", original_scope(start, clean=True), now=now)[0][1]["status"] == "RUNNING"
    assert lib.TestFacts_Writes() == writes and not facts(runtime, now)["cleanLockPowered"] and execution
    if case in {"future_poll", "old_poll"}:
        assert lib.McuWorkPreparation_Poll(preparation, endpoint, now)
        assert held_result(runtime, start, now)["completedUptimeMs"] == failed["uptimeMs"]


def test_expiry_and_update_after_failed_attempt_do_not_rewrite_or_block_its_historical_result(runtime, tmp_path):
    execution = enable(runtime)
    start, failed, now = prepared(runtime, tmp_path, clean=True, mode="unavailable", saved=False)
    runtime[0].ActuatorRuntime_StopForUpdate()
    now = advance(runtime, now, start["operationWindowMs"])
    store = EdgeStore(str(tmp_path / "late-preunlock.db"))
    store.initialize()
    try:
        save_intent(runtime, start, NAME, 0, now, store)
        now = advance(runtime, now, 0)
        result = held_result(runtime, start, now)
        assert result["completedUptimeMs"] == failed["uptimeMs"] == 5000
        assert result["finishReason"] == "FAILED" and result["initialKind"] == "UNAVAILABLE"
        assert facts(runtime, now)["updateLatched"] and not facts(runtime, now)["cleanLockPowered"]
        assert result["finalKind"] == "NOT_TAKEN" and not result["physicalCloseConfirmed"] and execution
    finally:
        store.close()


def test_clean_owner_does_not_finalize_failed_delivery_without_delivery_owner(runtime, tmp_path):
    execution = enable(runtime)
    start, failed, now = prepared(runtime, tmp_path, mode="unavailable", saved=True)
    now = advance(runtime, now, 60000)
    state = exchange(runtime, "QUERY_WORK", original_scope(start), now=now)[0][1]
    assert state["status"] == "RUNNING" and state["workType"] == "DELIVERY_SESSION"
    assert failed["measurementKind"] == "UNAVAILABLE" and events(runtime, now)[0][1]["status"] == "NOT_FOUND"
    assert not facts(runtime, now)["cleanLockPowered"] and execution


def test_failed_new_clean_does_not_inherit_previous_successful_clean_confirmation_or_final_weight(runtime, tmp_path):
    from hardware.tests.test_mcu_clean_confirmation import measured_candidate, confirm
    from hardware.tests.test_mcu_clean_confirmation import NAME as CONFIRMATION
    execution, previous, _, final, now, store = measured_candidate(runtime, tmp_path)
    try:
        assert confirm(runtime, execution, previous, final, now)
        save_intent(runtime, previous, CONFIRMATION, 1, now, store)
        now = advance(runtime, now, 0)
        old_result = held_result(runtime, previous, now)
        old_raw = uart.encode_payload("WORK_RESULT", old_result)
        receipt = store.save_native_mcu_result(old_raw)
        assert exchange(runtime, "RESULT_SAVED", payload=receipt["savedPayload"], now=now)[0][1]["status"] == "RELEASED"
        # New, separately authorized work at the C boundary, after result-slot
        # release. This does not simulate or claim Pi/cloud business admission.
        start = start_values("START_CLEAN_OPERATION", commandSequence=8,
            mcuCommandUid="88888888-8888-4888-8888-888888888888", operationUid="99999999-9999-4999-8999-999999999999")
        assert exchange(runtime, "START_CLEAN_OPERATION", start, now=now)[0][1]["outcome"] == "ACCEPTED"
        now = advance(runtime, now, 5000)
        failed = save_intent(runtime, start, NAME, 0, now, store)
        now = advance(runtime, now, 0)
        result = held_result(runtime, start, now)
        assert result["resultSequence"] == 2 and result["cleanActionSequence"] == 0
        assert result["originCommandUid"] == start["mcuCommandUid"] != previous["mcuCommandUid"]
        assert not result["physicalCloseConfirmed"] and result["finalKind"] == "NOT_TAKEN"
        assert result["initialMeasurementUid"] == failed["measurementUid"] != old_result["finalMeasurementUid"]
        assert result["initialKind"] == "UNAVAILABLE" and result["finishReason"] == "FAILED"
        assert store.get_native_mcu_result(42, 1)["payload"] == old_raw
        assert facts(runtime, now)["measurementSequence"] == 3 and not facts(runtime, now)["cleanLockPowered"]
        assert events(runtime, now)[0][1]["status"] == "NOT_FOUND"
    finally:
        store.close()


def failed_initial(runtime, tmp_path, kind):
    execution = enable(runtime)
    if kind == "UNAVAILABLE":
        start, failed, now = prepared(runtime, tmp_path, clean=True, mode="unavailable", saved=False)
    else:
        configured(runtime, applied=True)
        start = start_values("START_CLEAN_OPERATION")
        assert exchange(runtime, "START_CLEAN_OPERATION", start)[0][1]["outcome"] == "ACCEPTED"
        now = take_samples(runtime, [300])
        lib, _, preparation, *_ = runtime
        assert lib.McuWeightRun_Interrupt(lib.TestPreparation_Weight(preparation), 1, now)
        now = advance(runtime, now, 0)
        scope = original_scope(start, clean=True) | {"eventMessageType": NAME, "stepSequence": 0, "configVersion": start["configVersion"]}
        failed = exchange(runtime, "QUERY_PROCESS_EVENT", scope, now=now)[1][1]
    return execution, start, failed, now


@pytest.mark.parametrize("kind", ["UNAVAILABLE", "INTERRUPTED"])
@pytest.mark.parametrize("stage,loss", [(stage, loss) for stage in ("process", "result")
    for loss in ("exception", "short", "lost", "reply_lost")])
def test_failed_preunlock_process_and_result_survive_pi_restart_and_lost_receipts_without_unlock(runtime, tmp_path, kind, stage, loss):
    from mcu_process_handoff import McuProcessEventHandoff
    from mcu_result_handoff import McuResultHandoff
    execution, start, failed, now = failed_initial(runtime, tmp_path, kind)
    lib, endpoint, preparation, replies, *_ = runtime
    scope = original_scope(start, clean=True) | {"eventMessageType": NAME, "stepSequence": 0, "configVersion": start["configVersion"]}
    raw_scope = uart.encode_payload("QUERY_PROCESS_EVENT", scope)[8:]
    original = uart.encode_payload(NAME, failed)
    path = str(tmp_path / "handoff.db")
    store = EdgeStore(path)
    store.initialize()
    assert store.acquire_work_slot("CLEAN", start["operationUid"], 1, {"phase": "NATIVE_CLEAN"})
    occupancy = store.get_work_slot()
    broken, sent, result_raw = True, [], None
    lost_message = "PROCESS_EVENT_SAVED" if stage == "process" else "RESULT_SAVED"

    def write(frame):
        decoded = uart.decode_frame(frame, sender_role="EDGE")
        name = decoded["messageName"]
        sent.append(name)
        if name in {"PROCESS_EVENT_SAVED", "RESULT_SAVED"}:
            reader = EdgeStore(path)
            reader.initialize()
            try:
                assert reader.get_native_process_receipt(raw_scope)["payload"] == original
                assert reader.get_work_slot() == occupancy
                if name == "PROCESS_EVENT_SAVED":
                    assert reader.get_native_process_receipt(raw_scope)["saved_payload"] == decoded["payload"]
                    assert reader.list_native_result_report_tasks() == []
                else:
                    assert reader.get_native_mcu_result(42, 1)["payload"] == result_raw
                    assert len(reader.list_native_result_report_tasks()) == 1
            finally:
                reader.close()
            if broken and name == lost_message:
                if loss == "exception":
                    raise OSError("synthetic preunlock failure receipt loss")
                if loss == "short":
                    return 1
                if loss == "lost":
                    return len(frame)
        assert lib.McuControlEndpoint_Feed(endpoint, frame, len(frame), now) == 1
        if broken and name == lost_message and loss == "reply_lost":
            replies.clear()
        return len(frame)

    def pump(client):
        while replies:
            client.accept_frame(replies.pop(0), now)

    try:
        replies.clear()
        identity = {key: value for key, value in scope.items() if key != "queryId"}
        client = McuProcessEventHandoff(store, write, identity)
        first_query = client.poll(now)
        pump(client)
        if stage == "process":
            assert client.last_write_error == {"exception": "WRITE_FAILED", "short": "SHORT_WRITE"}.get(loss)
        store.close()
        store = EdgeStore(path)
        store.initialize()
        broken = stage == "result"
        client = McuProcessEventHandoff(store, write, identity)
        now = advance(runtime, now, 1000, poll=False)
        assert client.poll(now) > first_query
        pump(client)
        now = advance(runtime, now, 1000, poll=False)
        client.poll(now)
        pump(client)
        assert client.observation(now)["status"] == "RELEASED"
        assert lib.McuWorkPreparation_Poll(preparation, endpoint, now)
        result = held_result(runtime, start, now)
        assert result["initialKind"] == kind and result["finalKind"] == "NOT_TAKEN"
        assert result["completedUptimeMs"] == failed["uptimeMs"] and result["finishReason"] == "FAILED"
        assert result["cleanActionSequence"] == 0 and not result["physicalCloseConfirmed"]
        result_raw = uart.encode_payload("WORK_RESULT", result)
        result_identity = uart.decode_payload("RESULT_SAVED", result_raw[:60])
        replies.clear()
        client = McuResultHandoff(store, write, result_identity)
        first_query = client.poll(now)
        pump(client)
        if stage == "result":
            assert client.last_write_error == {"exception": "WRITE_FAILED", "short": "SHORT_WRITE"}.get(loss)
        store.close()
        store = EdgeStore(path)
        store.initialize()
        broken = False
        client = McuResultHandoff(store, write, result_identity)
        now = advance(runtime, now, 1000)
        assert client.poll(now) > first_query
        pump(client)
        now = advance(runtime, now, 1000)
        client.poll(now)
        pump(client)
        assert client.query_observation(now)["status"] == "RELEASED"
        assert store.get_native_process_receipt(raw_scope)["payload"] == original
        assert store.get_native_mcu_result(42, 1)["payload"] == result_raw
        assert store.get_work_slot() == occupancy
        assert [row["state"] for row in store.list_native_result_report_tasks()] == ["PENDING_CLASSIFICATION"]
        assert set(sent) == {"QUERY_PROCESS_EVENT", "PROCESS_EVENT_SAVED", "QUERY_RESULT", "RESULT_SAVED"}
        assert facts(runtime, now)["measurementSequence"] == 1 and not facts(runtime, now)["cleanLockPowered"]
        assert not facts(runtime, now)["pb6Output"] and not facts(runtime, now)["pb7Output"]
        assert events(runtime, now)[0][1]["status"] == "NOT_FOUND" and execution
        assert not lib.McuWeightRun_StartOwnedAttempt(lib.TestPreparation_Weight(preparation), now)
    finally:
        store.close()


@pytest.mark.parametrize("stage,expected", [("unsaved", "BUSY"), ("saved", "STATE_CONFLICT"), ("result", "UNKNOWN_WORK")])
def test_late_unlock_cannot_start_after_initial_weight_failure_and_cached_start_cannot_remeasure(runtime, tmp_path, stage, expected):
    execution = enable(runtime)
    assert runtime[0].ActuatorRuntime_SetDoorTarget(1)
    start, failed, now = prepared(runtime, tmp_path, clean=True, mode="unavailable", saved=stage != "unsaved")
    if stage == "result":
        now = advance(runtime, now, 0)
        assert held_result(runtime, start, now)["finishReason"] == "FAILED"
    assert exchange(runtime, "START_CLEAN_OPERATION", start, now=now)[0][1]["outcome"] == "ACCEPTED"
    name, command = grant(start, failed, clean=True)
    decision = exchange(runtime, name, command, now=now)[0][1]
    assert decision["outcome"] == "REJECTED" and decision["errorCode"] == expected
    now = advance(runtime, now, 1000)
    assert exchange(runtime, name, command, now=now)[0][1] == decision
    assert facts(runtime, now)["measurementSequence"] == 1 and not facts(runtime, now)["cleanLockPowered"]
    assert events(runtime, now)[0][1]["status"] == "NOT_FOUND" and execution


def test_initial_failure_result_does_not_consume_another_critical_process_event_number(runtime, tmp_path):
    execution = enable(runtime)
    start, failed, now = prepared(runtime, tmp_path, clean=True, mode="unavailable", saved=True)
    runtime[0].TestPreparation_SetEventSequence(runtime[1], 2**32 - 1)
    now = advance(runtime, now, 0)
    result = held_result(runtime, start, now)
    assert result["resultSequence"] == 1 and result["initialMcuEventSequence"] == failed["mcuEventSequence"]
    assert result["finishReason"] == "FAILED" and not facts(runtime, now)["cleanLockPowered"] and execution


def test_pi_commit_failure_keeps_failed_preunlock_record_held_without_final_result(runtime, tmp_path):
    import sqlite3
    from mcu_process_handoff import McuProcessEventHandoff
    execution, start, failed, now = failed_initial(runtime, tmp_path, "UNAVAILABLE")
    lib, endpoint, _, replies, *_ = runtime
    identity = {key: value for key, value in original_scope(start, clean=True).items() if key != "queryId"} | {
        "eventMessageType": NAME, "stepSequence": 0, "configVersion": start["configVersion"]}
    store = EdgeStore(str(tmp_path / "commit-failure.db"))
    store.initialize()
    sent = []

    def write(frame):
        sent.append(uart.decode_frame(frame, sender_role="EDGE")["messageName"])
        assert lib.McuControlEndpoint_Feed(endpoint, frame, len(frame), now) == 1
        return len(frame)

    try:
        replies.clear()
        client = McuProcessEventHandoff(store, write, identity)
        client.poll(now)
        assert client.accept_frame(replies.pop(0), now)
        event = replies.pop(0)
        store._conn.set_authorizer(lambda action, first, *_:
            sqlite3.SQLITE_DENY if action == sqlite3.SQLITE_TRANSACTION and first == "COMMIT" else sqlite3.SQLITE_OK)
        with pytest.raises(sqlite3.DatabaseError):
            client.accept_frame(event, now)
        store._conn.set_authorizer(None)
        assert sent == ["QUERY_PROCESS_EVENT"]
        assert store.get_native_process_event(NAME, 42, failed["mcuEventSequence"]) is None
        now = advance(runtime, now, 1000)
        assert exchange(runtime, "QUERY_PROCESS_EVENT", identity | {"queryId": 1}, now=now)[0][1]["status"] == "HELD"
        assert exchange(runtime, "QUERY_WORK", original_scope(start, clean=True), now=now)[0][1]["status"] == "RUNNING"
        assert store.list_native_result_report_tasks() == [] and not facts(runtime, now)["cleanLockPowered"] and execution
    finally:
        store._conn.set_authorizer(None)
        store.close()
