package org.enveloping.ecobin.identity.infrastructure.development;

import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.DefaultApplicationArguments;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.mock.env.MockEnvironment;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;

import java.time.LocalDateTime;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DevelopmentPlatformAdminInitializerTest {

    private JdbcTemplate jdbc;
    private PasswordEncoder passwordEncoder;
    private DevelopmentPlatformAdminProperties properties;
    private MockEnvironment environment;

    @BeforeEach
    void setUp() {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL(
                "jdbc:h2:mem:default_admin_"
                        + UUID.randomUUID()
                        + ";MODE=MySQL;DB_CLOSE_DELAY=-1");
        jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("""
                CREATE TABLE iam_platform_admin (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    platform_admin_uid VARCHAR(36) NOT NULL UNIQUE,
                    login_name VARCHAR(64) NOT NULL UNIQUE,
                    password_hash VARCHAR(255) NOT NULL,
                    display_name VARCHAR(100) NOT NULL,
                    enabled TINYINT NOT NULL,
                    failed_login_count INT NOT NULL,
                    locked_until TIMESTAMP(3) NULL,
                    auth_version BIGINT NOT NULL,
                    password_changed_at TIMESTAMP(3) NOT NULL,
                    lock_version BIGINT NOT NULL,
                    created_at TIMESTAMP(3) NOT NULL,
                    updated_at TIMESTAMP(3) NOT NULL
                )
                """);
        passwordEncoder = new BCryptPasswordEncoder(4);
        properties = new DevelopmentPlatformAdminProperties();
        environment = new MockEnvironment()
                .withProperty("ecobin.external.mode", "fake");
    }

    @Test
    void createsKnownAdministratorOnceWithoutResettingItsPassword() {
        DevelopmentPlatformAdminInitializer initializer = initializer();

        initializer.run(new DefaultApplicationArguments(new String[0]));
        String firstHash = jdbc.queryForObject("""
                        SELECT password_hash
                        FROM iam_platform_admin
                        WHERE login_name = 'admin'
                        """,
                String.class);
        assertTrue(passwordEncoder.matches("admin123", firstHash));
        assertEquals("开发平台管理员", jdbc.queryForObject("""
                        SELECT display_name
                        FROM iam_platform_admin
                        WHERE login_name = 'admin'
                        """,
                String.class));

        initializer.run(new DefaultApplicationArguments(new String[0]));
        assertEquals(1L, administratorCount());
        assertEquals(firstHash, jdbc.queryForObject("""
                        SELECT password_hash
                        FROM iam_platform_admin
                        WHERE login_name = 'admin'
                        """,
                String.class));
    }

    @Test
    void skipsDefaultWhenAnyPlatformAdministratorAlreadyExists() {
        LocalDateTime now = LocalDateTime.now();
        jdbc.update("""
                        INSERT INTO iam_platform_admin (
                            platform_admin_uid, login_name,
                            password_hash, display_name, enabled,
                            failed_login_count, locked_until,
                            auth_version, password_changed_at,
                            lock_version, created_at, updated_at
                        ) VALUES (?, 'custom-admin', ?, '已有管理员', 1,
                                  0, NULL, 0, ?, 0, ?, ?)
                        """,
                UUID.randomUUID().toString(),
                passwordEncoder.encode("CustomPass123!"),
                now,
                now,
                now);

        initializer().run(
                new DefaultApplicationArguments(new String[0]));

        assertEquals(1L, administratorCount());
        assertEquals(0L, jdbc.queryForObject("""
                        SELECT COUNT(*)
                        FROM iam_platform_admin
                        WHERE login_name = 'admin'
                        """,
                Long.class));
    }

    @Test
    void refusesRealExternalModeBeforeWriting() {
        environment.setProperty("ecobin.external.mode", "real");

        assertThrows(
                IllegalStateException.class,
                () -> initializer().run(
                        new DefaultApplicationArguments(new String[0])));
        assertEquals(0L, administratorCount());
    }

    @Test
    void refusesProductionProfileEvenWhenExternalModeIsFake() {
        environment.setActiveProfiles("production");

        assertThrows(
                IllegalStateException.class,
                () -> initializer().run(
                        new DefaultApplicationArguments(new String[0])));
        assertEquals(0L, administratorCount());
    }

    private DevelopmentPlatformAdminInitializer initializer() {
        return new DevelopmentPlatformAdminInitializer(
                jdbc,
                passwordEncoder,
                properties,
                environment);
    }

    private long administratorCount() {
        Long count = jdbc.queryForObject(
                "SELECT COUNT(*) FROM iam_platform_admin",
                Long.class);
        return count == null ? -1 : count;
    }
}
