package org.enveloping.ecobin.identity.infrastructure.bootstrap;

import org.enveloping.ecobin.framework.audit.AuditEntry;
import org.enveloping.ecobin.framework.audit.AuditPort;
import org.enveloping.ecobin.framework.audit.SuccessfulAudit;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DefaultPlatformAdminBootstrapServiceTest {

    private static final String TEST_PASSWORD = "BootstrapPass123!";

    private JdbcTemplate jdbc;
    private PasswordEncoder passwordEncoder;
    private DefaultPlatformAdminProperties properties;
    private RecordingAuditPort auditPort;

    @BeforeEach
    void setUp() {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL(
                "jdbc:h2:mem:default_admin_"
                        + UUID.randomUUID()
                        + ";MODE=MySQL;DB_CLOSE_DELAY=-1");
        jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("""
                CREATE TABLE iam_platform_admin (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    platform_admin_uid VARCHAR(36) NOT NULL UNIQUE,
                    admin_kind VARCHAR(16) NOT NULL,
                    login_name VARCHAR(64) NOT NULL UNIQUE,
                    password_hash VARCHAR(255) NOT NULL,
                    display_name VARCHAR(100) NOT NULL,
                    enabled TINYINT NOT NULL,
                    failed_login_count INT NOT NULL,
                    locked_until TIMESTAMP(3) NULL,
                    auth_version BIGINT NOT NULL,
                    password_changed_at TIMESTAMP(3) NOT NULL,
                    deleted_at TIMESTAMP(3) NULL,
                    lock_version BIGINT NOT NULL,
                    created_at TIMESTAMP(3) NOT NULL,
                    updated_at TIMESTAMP(3) NOT NULL
                )
                """);
        passwordEncoder = new BCryptPasswordEncoder(4);
        properties = new DefaultPlatformAdminProperties();
        properties.setEnabled(true);
        properties.setPassword(TEST_PASSWORD);
        auditPort = new RecordingAuditPort();
    }

    @Test
    void createsTheProtectedAdministratorOnceWithoutResettingIt() {
        DefaultPlatformAdminBootstrapService service = service();

        assertTrue(service.ensureDefaultAdministrator());
        String firstHash = jdbc.queryForObject("""
                        SELECT password_hash
                        FROM iam_platform_admin
                        WHERE login_name = 'enveloping'
                        """,
                String.class);
        assertTrue(passwordEncoder.matches(TEST_PASSWORD, firstHash));
        assertEquals("DEFAULT", jdbc.queryForObject("""
                        SELECT admin_kind
                        FROM iam_platform_admin
                        WHERE login_name = 'enveloping'
                        """,
                String.class));
        assertEquals("默认平台管理员", jdbc.queryForObject("""
                        SELECT display_name
                        FROM iam_platform_admin
                        WHERE login_name = 'enveloping'
                        """,
                String.class));
        assertEquals(1, auditPort.entries.size());

        properties.setPassword("DifferentPass123!");
        assertFalse(service.ensureDefaultAdministrator());
        assertEquals(1L, administratorCount());
        assertEquals(firstHash, jdbc.queryForObject("""
                        SELECT password_hash
                        FROM iam_platform_admin
                        WHERE login_name = 'enveloping'
                        """,
                String.class));
        assertEquals(1, auditPort.entries.size());
    }

    @Test
    void acceptsAnExistingConsistentDefaultAdministrator() {
        insertAdministrator("DEFAULT", "existing-default");

        assertFalse(service().ensureDefaultAdministrator());
        assertEquals(1L, administratorCount());
        assertEquals(0, auditPort.entries.size());
    }

    @Test
    void refusesToElevateAnOrdinaryAdministrator() {
        insertAdministrator("STANDARD", "ordinary-admin");

        IllegalStateException failure = assertThrows(
                IllegalStateException.class,
                () -> service().ensureDefaultAdministrator());

        assertTrue(failure.getMessage().contains("inconsistent"));
        assertEquals(1L, administratorCount());
    }

    @Test
    void requiresAnExternalPasswordOnlyForAnEmptyDirectory() {
        properties.setPassword("");

        assertThrows(
                IllegalStateException.class,
                () -> service().ensureDefaultAdministrator());
        assertEquals(0L, administratorCount());
    }

    private DefaultPlatformAdminBootstrapService service() {
        return new DefaultPlatformAdminBootstrapService(
                jdbc,
                passwordEncoder,
                auditPort,
                properties);
    }

    private void insertAdministrator(String kind, String loginName) {
        LocalDateTime now = LocalDateTime.now();
        jdbc.update("""
                        INSERT INTO iam_platform_admin (
                            platform_admin_uid, admin_kind, login_name,
                            password_hash, display_name, enabled,
                            failed_login_count, locked_until,
                            auth_version, password_changed_at, deleted_at,
                            lock_version, created_at, updated_at
                        ) VALUES (?, ?, ?, ?, '已有管理员', 1,
                                  0, NULL, 0, ?, NULL, 0, ?, ?)
                        """,
                UUID.randomUUID().toString(),
                kind,
                loginName,
                passwordEncoder.encode("ExistingPass123!"),
                now,
                now,
                now);
    }

    private long administratorCount() {
        Long count = jdbc.queryForObject(
                "SELECT COUNT(*) FROM iam_platform_admin", Long.class);
        return count == null ? -1 : count;
    }

    private static final class RecordingAuditPort implements AuditPort {

        private final List<AuditEntry> entries = new ArrayList<>();

        @Override
        public Optional<SuccessfulAudit> findSuccessful(UUID operationUid) {
            return Optional.empty();
        }

        @Override
        public long append(AuditEntry entry) {
            entries.add(entry);
            return entries.size();
        }
    }
}
