package org.enveloping.ecobin.identity.application.directory;

import org.enveloping.ecobin.framework.audit.AuditEntry;
import org.enveloping.ecobin.framework.audit.AuditPort;
import org.enveloping.ecobin.framework.audit.SuccessfulAudit;
import org.enveloping.ecobin.framework.context.TrustedAudience;
import org.enveloping.ecobin.framework.web.v1.TargetApiException;
import org.enveloping.ecobin.identity.application.web.TargetWebActor;
import org.enveloping.ecobin.identity.application.web.TargetWebActorContext;
import org.enveloping.ecobin.identity.application.web.WebAccountType;
import org.enveloping.ecobin.identity.infrastructure.persistence.v1.TargetIdentitySessionRepository;
import org.enveloping.ecobin.identity.web.v1.directory.DirectoryModels.AccountVersionCommand;
import org.enveloping.ecobin.identity.web.v1.directory.DirectoryModels.ChangeOwnPasswordRequest;
import org.enveloping.ecobin.identity.web.v1.directory.DirectoryModels.ResetPasswordRequest;
import org.enveloping.ecobin.identity.web.v1.directory.PlatformAdminModels.CreatePlatformAdminRequest;
import org.enveloping.ecobin.identity.web.v1.directory.PlatformAdminModels.DeletePlatformAdminRequest;
import org.enveloping.ecobin.identity.web.v1.directory.PlatformAdminModels.PlatformAdminView;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;
import tools.jackson.databind.ObjectMapper;
import tools.jackson.databind.json.JsonMapper;

import java.time.Instant;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;

class TargetPlatformAdminAccountServiceTest {

    private static final String ROOT_PASSWORD = "RootPassword123!";
    private static final String USER_PASSWORD = "UserPassword123!";

    private JdbcTemplate jdbc;
    private PasswordEncoder passwordEncoder;
    private TargetIdentitySessionRepository sessionRepository;
    private RecordingAuditPort auditPort;
    private TargetPlatformAdminAccountService service;
    private Administrator root;

    @BeforeEach
    void setUp() {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL(
                "jdbc:h2:mem:platform_admin_"
                        + UUID.randomUUID()
                        + ";MODE=MySQL;DB_CLOSE_DELAY=-1");
        jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("""
                CREATE TABLE iam_platform_admin (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    platform_admin_uid VARCHAR(36) NOT NULL UNIQUE,
                    admin_kind VARCHAR(16) NOT NULL,
                    login_name VARCHAR(64) NOT NULL UNIQUE,
                    password_hash VARCHAR(255) NOT NULL,
                    display_name VARCHAR(100) NOT NULL,
                    enabled TINYINT NOT NULL,
                    failed_login_count INT NOT NULL,
                    locked_until TIMESTAMP(3) NULL,
                    auth_version BIGINT NOT NULL,
                    password_changed_at TIMESTAMP(3) NOT NULL,
                    deleted_at TIMESTAMP(3) NULL,
                    lock_version BIGINT NOT NULL,
                    created_at TIMESTAMP(3) NOT NULL,
                    updated_at TIMESTAMP(3) NOT NULL
                )
                """);
        passwordEncoder = new BCryptPasswordEncoder(4);
        sessionRepository = mock(TargetIdentitySessionRepository.class);
        auditPort = new RecordingAuditPort();
        ObjectMapper objectMapper = JsonMapper.builder()
                .findAndAddModules()
                .build();
        service = new TargetPlatformAdminAccountService(
                jdbc,
                passwordEncoder,
                sessionRepository,
                auditPort,
                objectMapper);
        root = insertAdministrator(
                "DEFAULT", "enveloping", ROOT_PASSWORD, true);
        TargetWebActorContext.set(actor(root, true));
    }

    @AfterEach
    void tearDown() {
        TargetWebActorContext.clear();
    }

    @Test
    void defaultAdministratorCreatesAndResetsAnOrdinaryAdministrator() {
        String initialPassword = "InitialPassword123!";
        PlatformAdminView created = service.createAdministrator(
                UUID.randomUUID(),
                new CreatePlatformAdminRequest(
                        "Ordinary.Admin",
                        initialPassword,
                        "普通管理员"));

        assertEquals("ordinary.admin", created.loginName());
        assertEquals("STANDARD", created.adminKind());
        assertEquals("ACTIVE", created.status());
        long targetId = id(created.platformAdminUid());
        assertTrue(passwordEncoder.matches(
                initialPassword, passwordHash(targetId)));

        String replacement = "ReplacementPassword123!";
        PlatformAdminView reset = service.resetPassword(
                UUID.randomUUID(),
                created.platformAdminUid(),
                new ResetPasswordRequest(
                        replacement,
                        created.version(),
                        created.authVersion()));

        assertEquals(created.version() + 1, reset.version());
        assertEquals(created.authVersion() + 1, reset.authVersion());
        assertTrue(passwordEncoder.matches(replacement, passwordHash(targetId)));
        verify(sessionRepository).revokeAllPlatformSessions(
                targetId, "PASSWORD_CHANGED");
        assertEquals(2, auditPort.entries.size());
        for (AuditEntry entry : auditPort.entries) {
            assertFalse(entry.safeChangeSummaryJson().contains(initialPassword));
            assertFalse(entry.safeChangeSummaryJson().contains(replacement));
        }
    }

    @Test
    void defaultAdministratorListsAdministratorsWithoutFilters() {
        var page = service.listAdministrators(1, 20, null, null);

        assertEquals(1L, page.total());
        assertEquals(1, page.items().size());
        assertEquals("enveloping", page.items().getFirst().loginName());
        assertEquals("DEFAULT", page.items().getFirst().adminKind());
    }

    @Test
    void ordinaryAdministratorCannotGovernOthersButCanChangeOwnPassword() {
        Administrator ordinary = insertAdministrator(
                "STANDARD", "ordinary", USER_PASSWORD, true);
        TargetWebActorContext.set(actor(ordinary, false));

        TargetApiException listFailure = assertThrows(
                TargetApiException.class,
                () -> service.listAdministrators(1, 20, null, null));
        assertEquals(403, listFailure.status());

        TargetApiException resetFailure = assertThrows(
                TargetApiException.class,
                () -> service.resetPassword(
                        UUID.randomUUID(),
                        root.uid(),
                        new ResetPasswordRequest("CannotUse123!", 0L, 0L)));
        assertEquals(403, resetFailure.status());

        String replacement = "OwnReplacement123!";
        PlatformAdminView changed = service.changeOwnPassword(
                UUID.randomUUID(),
                new ChangeOwnPasswordRequest(
                        USER_PASSWORD,
                        replacement,
                        0L,
                        0L));
        assertEquals(1L, changed.authVersion());
        assertTrue(passwordEncoder.matches(
                replacement, passwordHash(ordinary.id())));
        verify(sessionRepository).revokeAllPlatformSessions(
                ordinary.id(), "PASSWORD_CHANGED");
    }

    @Test
    void defaultAdministratorIsProtectedFromGovernanceCommands() {
        TargetApiException deactivateFailure = assertThrows(
                TargetApiException.class,
                () -> service.changeStatus(
                        UUID.randomUUID(),
                        root.uid(),
                        new AccountVersionCommand(0L, 0L, "不允许"),
                        false));
        assertEquals(
                "IDENTITY.DEFAULT_PLATFORM_ADMIN_PROTECTED",
                deactivateFailure.code());

        TargetApiException resetFailure = assertThrows(
                TargetApiException.class,
                () -> service.resetPassword(
                        UUID.randomUUID(),
                        root.uid(),
                        new ResetPasswordRequest("NoReset123!", 0L, 0L)));
        assertEquals(
                "IDENTITY.DEFAULT_PLATFORM_ADMIN_PROTECTED",
                resetFailure.code());

        TargetApiException deleteFailure = assertThrows(
                TargetApiException.class,
                () -> service.deleteAdministrator(
                        UUID.randomUUID(),
                        root.uid(),
                        new DeletePlatformAdminRequest(0L, 0L, "不允许")));
        assertEquals(
                "IDENTITY.DEFAULT_PLATFORM_ADMIN_PROTECTED",
                deleteFailure.code());
    }

    @Test
    void logicalDeletionIsPermanentAndKeepsLoginNameReserved() {
        Administrator ordinary = insertAdministrator(
                "STANDARD", "delete-me", USER_PASSWORD, true);

        PlatformAdminView deleted = service.deleteAdministrator(
                UUID.randomUUID(),
                ordinary.uid(),
                new DeletePlatformAdminRequest(0L, 0L, "账号不再使用"));

        assertEquals("DELETED", deleted.status());
        assertNotNull(deleted.deletedAt());
        assertEquals(0, jdbc.queryForObject(
                "SELECT enabled FROM iam_platform_admin WHERE id = ?",
                Integer.class,
                ordinary.id()));
        verify(sessionRepository).revokeAllPlatformSessions(
                ordinary.id(), "PLATFORM_ADMIN_DELETED");

        TargetApiException restoreFailure = assertThrows(
                TargetApiException.class,
                () -> service.changeStatus(
                        UUID.randomUUID(),
                        ordinary.uid(),
                        new AccountVersionCommand(
                                deleted.version(),
                                deleted.authVersion(),
                                "尝试恢复"),
                        true));
        assertEquals("IDENTITY.PLATFORM_ADMIN_DELETED", restoreFailure.code());

        TargetApiException reuseFailure = assertThrows(
                TargetApiException.class,
                () -> service.createAdministrator(
                        UUID.randomUUID(),
                        new CreatePlatformAdminRequest(
                                ordinary.loginName(),
                                "AnotherPassword123!",
                                "重用登录名")));
        assertEquals(
                "IDENTITY.PLATFORM_ADMIN_LOGIN_ALREADY_USED",
                reuseFailure.code());
    }

    private Administrator insertAdministrator(
            String kind,
            String loginName,
            String password,
            boolean enabled) {
        UUID uid = UUID.randomUUID();
        LocalDateTime now = LocalDateTime.now();
        jdbc.update("""
                        INSERT INTO iam_platform_admin (
                            platform_admin_uid, admin_kind, login_name,
                            password_hash, display_name, enabled,
                            failed_login_count, locked_until,
                            auth_version, password_changed_at, deleted_at,
                            lock_version, created_at, updated_at
                        ) VALUES (?, ?, ?, ?, ?, ?, 0, NULL, 0, ?, NULL, 0, ?, ?)
                        """,
                uid.toString(),
                kind,
                loginName,
                passwordEncoder.encode(password),
                loginName,
                enabled,
                now,
                now,
                now);
        return new Administrator(id(uid), uid, loginName, enabled);
    }

    private long id(UUID uid) {
        Long result = jdbc.queryForObject(
                "SELECT id FROM iam_platform_admin WHERE platform_admin_uid = ?",
                Long.class,
                uid.toString());
        return result == null ? -1 : result;
    }

    private String passwordHash(long id) {
        return jdbc.queryForObject(
                "SELECT password_hash FROM iam_platform_admin WHERE id = ?",
                String.class,
                id);
    }

    private static TargetWebActor actor(
            Administrator administrator,
            boolean mayGovern) {
        return new TargetWebActor(
                WebAccountType.PLATFORM_ADMIN,
                TrustedAudience.WEB_PLATFORM,
                administrator.id(),
                administrator.uid(),
                null,
                null,
                null,
                UUID.randomUUID(),
                administrator.loginName(),
                null,
                0,
                0,
                Instant.parse("2030-01-01T00:00:00Z"),
                mayGovern ? Set.of("platform-account.manage") : Set.of(),
                List.of());
    }

    private record Administrator(
            long id,
            UUID uid,
            String loginName,
            boolean enabled) {
    }

    private static final class RecordingAuditPort implements AuditPort {

        private final List<AuditEntry> entries = new ArrayList<>();

        @Override
        public Optional<SuccessfulAudit> findSuccessful(UUID operationUid) {
            return Optional.empty();
        }

        @Override
        public long append(AuditEntry entry) {
            entries.add(entry);
            return entries.size();
        }
    }
}
